---
pipelines:
  - name: verify
    triggers:
      - event: DRAFT_PUBLISHED
      - event: PATCHSET_CREATED
      - event: CHANGE_RESTORED
      - event: COMMENT_ADDED
        commentFilter: (?i)^(Patch Set [0-9]+:)?( [\w\\+-]*)*(\n\n)?\s*(recheck|reverify)
    onStart:
      - approval: VERIFIED
        score: 0
    onSuccess:
      - approval: VERIFIED
        score: 1
    onFailure:
      - approval: VERIFIED
        score: -1
  - name: qa
    triggers:
      - event: DRAFT_PUBLISHED
      - event: PATCHSET_CREATED
      - event: CHANGE_RESTORED
      - event: COMMENT_ADDED
        commentFilter: (?i)^(Patch Set [0-9]+:)?( [\w\\+-]*)*(\n\n)?\s*(recheck( qa)?)
    onStart:
      - approval: QUALITY_ASSURANCE
        score: 0
    onSuccess:
      - approval: QUALITY_ASSURANCE
        score: 1
    onFailure:
      - approval: QUALITY_ASSURANCE
        score: -1
  - name: post
    triggers:
      - event: COMMENT_ADDED
        commentFilter: (?i)^(Patch Set [0-9]+:)?( [\w\\+-]*)*(\n\n)?\s*(revalidate)
      - event: COMMENT_ADDED
        approvals:
          - approval: CODE_REVIEW
            score: 2
          - approval: QUALITY_ASSURANCE
            score: 1
          - approval: WORKFLOW
            score: 1
          - approval: VERIFIED
            score: 1
    onStart:
      - approval: VERIFIED
        score: 0
    onSuccess:
      - approval: VERIFIED
        score: 2
      - approval: SUBMIT
    onFailure:
      - approval: VERIFIED
        score: -2

projects:
  - name: ^games/.*$
    verify:
      - noop
    qa:
      - gate-check-python-pep8
      - gate-check-shell-scripts
      - gate-check-trailing-whitespaces
    post:
      - noop

  - name: ^linaDevel/nemesis$
    verify:
      - verify-nemesis
    qa:
      - gate-check-python-pep8
      - gate-check-shell-scripts
      - gate-check-trailing-whitespaces
    post:
      - gate-nemesis

  - name: ^linaDevel/nemesisConfig$
    verify:
      - gate-validate-nemesis-config
    qa:
      - gate-check-python-pep8
      - gate-check-shell-scripts
      - gate-check-trailing-whitespaces
    post:
      - gate-install-nemesis-config

  - name: ^linaDevel/darkGerritTheme$
    verify:
      - noop
    qa:
      - gate-check-python-pep8
      - gate-check-shell-scripts
      - gate-check-trailing-whitespaces
    post:
      - post-install-gerrit-theme

  - name: ^linaDevel/.*Scripts$
    verify:
      - noop
    qa:
      - gate-check-python-pep8
      - gate-check-shell-scripts
      - gate-check-trailing-whitespaces
    post:
      - noop
  - name: ^linaDevel/plexAgents$
    verify:
     - noop
    qa:
      - gate-check-python-pep8
      - gate-check-shell-scripts
      - gate-check-trailing-whitespaces
    post:
      - noop
  - name: ^yggdrasilProject/.*Plugin$
    verify:
      - gate-verify-yggdrasil-plugin
    qa:
      - gate-check-python-pep8
      - gate-check-shell-scripts
      - gate-check-trailing-whitespaces
    post:
      - gate-build-yggdrasil-plugin
  - name: ^yggdrasilProject/yggdrasil.*$
    verify:
      - gate-verify-yggdrasil
    qa:
      - gate-check-python-pep8
      - gate-check-shell-scripts
      - gate-check-trailing-whitespaces
    post:
      - gate-build-yggdrasil
  - name: ^infernoProject/.*$
    verify:
      - gate-verify-inferno
    qa:
      - gate-check-python-pep8
      - gate-check-shell-scripts
      - gate-check-trailing-whitespaces
    post:
      - gate-build-inferno
  - name: ^openstack/.*$
    qa:
      - noop
  - name: ^v0rt3xProject/vindicator.*$
    verify:
      - gate-verify-vindicator
    qa:
      - gate-check-python-pep8
      - gate-check-shell-scripts
      - gate-check-trailing-whitespaces
    post:
      - gate-build-vindicator
  - name: ^v0rt3xProject/.*$
    verify:
      - noop
    qa:
      - gate-check-python-pep8
      - gate-check-shell-scripts
      - gate-check-trailing-whitespaces
    post:
      - noop
