jobs:
 - name: gate-check-trailing-whitespaces
   voting: true
   builders:
    ShellBuilder:
     script: |
      set +e

      echo "List of files with trailing whitespaces:"
      grep --exclude-dir ".git" -Irl '[[:blank:]]$' ./source
      sleep 1
      if [[ $? -eq 0 ]]; then
        echo "Trailing whitespaces found!"
        exit 1
      else
        echo "No files found!"
        exit 0
      fi
