jobs:
 - name: gate-check-trailing-whitespaces
   voting: false
   builders:
    ShellBuilder:
     script: | 
      set +e
      RES=$(grep -Irl '[[:blank:]]$' ./source/*)
      if [[ $? -eq 0 ]]; then
        echo "Trailing whitespaces found:"
        echo -e "${RES}"
        exit 1
      else 
        echo "OK"
        exit 0
      fi
