jobs:
 - name: gate-check-trailing-whitespaces
   voting: true
   builders:
    ShellBuilder:
     script: |
      set +e

      echo "List of files with trailing whitespaces:"
      grep --exclude-dir ".git" -Irl '[[:blank:]]$' ./source
      if [[ $? -eq 0 ]]; then
        echo "Trailing whitespaces found!"
        sleep 1
        exit 1
      else
        echo "No files found!"
        sleep 1
        exit 0
      fi
 - name: gate-check-shell-scripts
   builders:
    ShellBuilder:
     script: |
      #!/bin/bash -xe
      for script in $(find "${WORKSPACE}/source/" -name *.sh); do
        shellcheck $script -e SC2086,SC2016,SC2034,SC2046,SC2140
      done
 - name: gate-check-python-pep8
   builders:
    ShellBuilder:
     script: |
      #!/bin/bash -xe
      pip install pep8
      pep8 ${WORKSPACE}/source/
