jobs:
  - name: gate-verify-core
    builders:
     MavenBuilder:
      target:
       - package
  - name: gate-build-core
    builders:
     MavenBuilder:
      target:
       - package
    publishers:
     LocalPublisher:
      source: '*.tar.gz'
      target: /var/www/artifacts/core
      checksum: true
