jobs:
  - name: gate-verify-core
    builders:
     MavenBuilder:
      target:
       - package
  - name: gate-build-core
    builders:
     ShellBuilder:
      script: |
       #!/bin/bash
       bash -xe "${WORKSPACE}/source/tools/prepare_tarball.sh"
       mkdir -p "${WORKSPACE}/artifacts/"
       TAR_FILE=$(basename $(find "${WORKSPACE}/source/" -maxdepth 1 -name '*.tar.gz' | tail -1))
       cp "${WORKSPACE}/source/${TAR_FILE}" "${WORKSPACE}/artifacts/"
    publishers:
     LocalPublisher:
      source: '*.tar.gz'
      target: /var/www/artifacts/core
      checksum: true
