jobs:
  - name: gate-verify-inferno
    builders:
     MavenBuilder:
      target:
       - package
      copyJar: true
  - name: gate-build-inferno
    builders:
     MavenBuilder:
      target:
       - package
      copyJar: true
    publishers:
     LocalPublisher:
      source: '*.jar'
      target: /var/www/artifacts/inferno
      checksum: true
