jobs:
  - name: gate-verify-yggdrasil
    builders:
     MavenBuilder:
      target:
       - package
  - name: gate-build-yggdrasil
    builders:
     ShellBuilder:
      script: |
       #!/bin/bash
       bash -xe "${WORKSPACE}/source/tools/prepare_tarball.sh"
       mkdir -p "${WORKSPACE}/artifacts/"
       TAR_FILE=$(basename $(find "${WORKSPACE}/source/" -maxdepth 1 -name '*.tar.gz' | tail -1))
       cp "${WORKSPACE}/source/${TAR_FILE}" "${WORKSPACE}/artifacts/"
    publishers:
     LocalPublisher:
      source: '*.tar.gz'
      target: /var/www/artifacts/yggdrasil
      checksum: true
  - name: gate-verify-yggdrasil-plugin
    builders:
     MavenBuilder:
      target:
       - clean
       - compile
       - assembly:single
  - name: gate-build-yggdrasil-plugin
    builders:
     MavenBuilder:
      target:
       - clean
       - compile
       - assembly:single
    publishers:
     LocalPublisher:
      source: '*.jar'
      target: /var/www/artifacts/yggdrasil-plugins
      checksum: true

